######################
#
#  Env
#
######################

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo =  'thinca/vim-singleton'
gui = 1

[[plugins]]
repo =  'deton/jasentence.vim'
if = '''!has('kaoriya')'''
on_i = 1

[[plugins]]
repo =  'deton/jasegment.vim'
if = '''!has('kaoriya')'''

[[plugins]]
repo =  'itchyny/lightline.vim'

[[plugins]]
repo =  'Yggdroot/indentLine'

[[plugins]]
repo =  'vim-scripts/AnsiEsc.vim'

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = 'let g:rainbow_active = 1'

[[plugins]]
repo =  'mattn/webapi-vim'
# ref[rmine:http://blog.basyura.org/entry/20130106/p1]

[[plugins]]
repo = 'vimwiki/vimwiki'
hook_add =  '''
    au BufNewFile,BufRead *.{wiki} set filetype=vimwiki
	let g:vimwiki_nested_syntaxes = {'python': 'python', 'c++': 'cpp', 'bash': 'sh'}
'''
on_ft = 'vimwiki'

#########################
#
# Utils
#
########################

[[plugins]]
repo =  'Shougo/neomru.vim'

[[plugins]]
repo =  'tyru/open-browser.vim'

[[plugins]]
repo =  'thinca/vim-quickrun'

# Writting Support
[[plugins]]
repo =  'terryma/vim-multiple-cursors'

[[plugins]]
repo =  'scrooloose/syntastic'

[[plugins]]
repo =  'kana/vim-textobj-user'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_add = '''
    let g:extra_whitespace_ignored_filetypes = ['unite', 'calendar', 'help', 'nerdtree', 'vimfiler', 'vimshell']
'''

# [[plugins]]
# repo =  'AndrewRadev/linediff.vim'

# Tagging
# [TODO] -I is not worked my mingw64. so I need to add include path to make
# file and build by my self.
#
# [[plugins]]
# hook_post_update = ''' has('win32') || has('win64')
#     if executable('mingw32-make')
#         let g:mingw_include = 'C:/bin/mingw64/include/'
#         let $PATH = $PATH .';# . g:mingw_include
#         repo =  'vim-jp/ctags', { 'build' : { 'windows' : 'mingw32-make.exe -I' . g:mingw_include . ' -f mk_mingw.mak' , } }
#     else
#         repo =  'vim-jp/ctags'
#     endif
#     if !exists('g:load_my_tag_path')
#         let g:load_my_tag_path = 1
#         # Add ctags to my repository
#         let $PATH = $PATH . ';# . $HOME . '/.vim/bundle/ctags'
#     endif
# endif
# '''

##########################
# Tools
##########################
[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'tyru/open-browser.vim'

##############
#
# Checker
#
#############
[[plugins]]
repo = 'osyo-manga/shabadou.vim'

[[plugins]]
repo = 'jceb/vim-hier'

[[plugins]]
repo =  'datsuns/astyle.vim'
if = '''executable('astyle')'''

#######################################################
#
# Color Scheme
#
#######################################################
[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'jonathanfilip/vim-lucius'

[[plugins]]
repo = 'chriskempson/vim-tomorrow-theme'

[[plugins]]
repo = 'taka-vagyok/term_forrest_cls.vim'

########################
#
# VCS
#
################################
[[plugins]]
repo = 'kmnk/vim-unite-giti'
if = '''executable('git')'''

[[plugins]]
repo =  'tpope/vim-fugitive'
if = '''executable('git')'''

[[plugins]]
repo =  'vim-scripts/vcscommand.vim'

