######################
#
#  Env
#
######################

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo =  'thinca/vim-singleton'
gui = 1

[[plugins]]
repo =  'deton/jasentence.vim'
if = '''!has('kaoriya')'''
on_i = 1

[[plugins]]
repo =  'deton/jasegment.vim'
if = '''!has('kaoriya')'''

[[plugins]]
repo =  'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {
    \ 'colorscheme': 'wombat',
    \ 'active': {
    \   'left': [ [ 'mode', 'paste' ],
    \             [ 'readonly', 'filename', 'modified' ],
    \             [ 'linter_checking', 'linter_errors', 'linter_warnings', 'linter_ok' ] ],
    \ },
    \ }
'''

[[plugins]]
repo = 'maximbaz/lightline-ale'
depends = ['lightline.vim', 'ale']
hook_add = '''
    let g:lightline.component_expand = {
      \  'linter_checking': 'lightline#ale#checking',
      \  'linter_warnings': 'lightline#ale#warnings',
      \  'linter_errors': 'lightline#ale#errors',
      \  'linter_ok': 'lightline#ale#ok',
      \ }
    let g:lightline.component_type = {
      \     'linter_checking': 'left',
      \     'linter_warnings': 'warning',
      \     'linter_errors': 'error',
      \     'linter_ok': 'left',
      \ }
    let g:lightline.active = {
      \ 'right': [[ 'linter_checking', 'linter_errors', 'linter_warnings', 'linter_ok'  ]]
      \ }
'''

[[plugins]]
repo =  'Yggdroot/indentLine'

[[plugins]]
repo =  'vim-scripts/AnsiEsc.vim'

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = 'let g:rainbow_active = 1'

[[plugins]]
repo =  'mattn/webapi-vim'
# ref[rmine:http://blog.basyura.org/entry/20130106/p1]

[[plugins]]
repo = 'vimwiki/vimwiki'
hook_add =  '''
    au BufNewFile,BufRead *.{wiki} set filetype=vimwiki
	let g:vimwiki_nested_syntaxes = {'python': 'python', 'c++': 'cpp', 'bash': 'sh'}
'''
on_ft = 'vimwiki'

#########################
#
# Utils
#
########################

[[plugins]]
repo =  'Shougo/neomru.vim'

[[plugins]]
repo =  'tyru/open-browser.vim'

[[plugins]]
repo =  'thinca/vim-quickrun'

# Writting Support
[[plugins]]
repo =  'terryma/vim-multiple-cursors'

#[[plugins]]
#repo =  'scrooloose/syntastic'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
    let g:ale_lint_on_text_changed = 1
    let g:ale_sign_error = '✖'
    let g:ale_sign_warning = '⚠ '
    let g:airline#extensions#ale#open_lnum_symbol = '('
    let g:airline#extensions#ale#close_lnum_symbol = ')'
    let g:ale_echo_msg_format = '[%linter%]%code: %%s'
    highlight link ALEErrorSign Tag
    highlight link ALEWarningSign StorageClass
    nmap <silent> <C-k> <Plug>(ale_previous_wrap)
    nmap <silent> <C-j> <Plug>(ale_next_wrap)

    let g:ale_linters = {
    \   'javascript': ['eslint', 'eslint-plugin-vue'],
    \   'python': ['pyflakes', 'pep8'],
    \   'ruby': ['rubocop'],
    \   'tex': ['textlint'],
    \   'markdown': ['textlint'],
    \   'css': ['stylelint'],
    \}
    let g:ale_completion_enabled = 1
'''

[[plugins]]
repo = 'pepo-le/win-ime-con.nvim'

[[plugins]]
repo =  'kana/vim-textobj-user'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_add = '''
    let g:extra_whitespace_ignored_filetypes = ['unite', 'calendar', 'help', 'nerdtree', 'vimfiler', 'vimshell']
'''

# [[plugins]]
# repo =  'AndrewRadev/linediff.vim'

# Tagging
# [TODO] -I is not worked my mingw64. so I need to add include path to make
# file and build by my self.
#
# [[plugins]]
# hook_post_update = ''' has('win32') || has('win64')
#     if executable('mingw32-make')
#         let g:mingw_include = 'C:/bin/mingw64/include/'
#         let $PATH = $PATH .';# . g:mingw_include
#         repo =  'vim-jp/ctags', { 'build' : { 'windows' : 'mingw32-make.exe -I' . g:mingw_include . ' -f mk_mingw.mak' , } }
#     else
#         repo =  'vim-jp/ctags'
#     endif
#     if !exists('g:load_my_tag_path')
#         let g:load_my_tag_path = 1
#         # Add ctags to my repository
#         let $PATH = $PATH . ';# . $HOME . '/.vim/bundle/ctags'
#     endif
# endif
# '''

##########################
# Tools
##########################
[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'tyru/open-browser.vim'

##############
#
# Checker
#
#############
[[plugins]]
repo = 'osyo-manga/shabadou.vim'

[[plugins]]
repo = 'jceb/vim-hier'

[[plugins]]
repo =  'datsuns/astyle.vim'
if = '''executable('astyle')'''

#######################################################
#
# Color Scheme
#
#######################################################
[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'jonathanfilip/vim-lucius'

[[plugins]]
repo = 'chriskempson/vim-tomorrow-theme'

[[plugins]]
repo = 'taka-vagyok/term_forrest_cls.vim'

########################
#
# VCS
#
################################
[[plugins]]
repo = 'kmnk/vim-unite-giti'
if = '''executable('git')'''

[[plugins]]
repo =  'tpope/vim-fugitive'
if = '''executable('git')'''

[[plugins]]
repo =  'vim-scripts/vcscommand.vim'

